version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: python_app_Docker-credentials-username
    DOCKER_REGISTRY_PASSWORD: python_app_docker_password
    DOCKER_REGISTRY_URL: python_app_docker_registry_url

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Upgrading pip..."
      - python -m pip install --upgrade pip
      - echo "Listing files at the root level..."
      - ls -l
      - echo "Identifying correct path to requirements.txt file..."

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt --verbose || { echo 'pip install failed'; exit 1; }

  build:
    commands:
      - echo "Running tests..."
      - cd Python-app/blob/main/Requirement.txt
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/Python-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/Python-app:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: ../Python-app
